### ISSUE TITLE
[leak] High CPU usage with a lot of subscribers

### ISSUE THREAD

**Issue by divine** [dunglas/mercure#558]
Hello,

This issue has been created to track down the problem that I'm having with Mercure:

Mercure uses almost %100 CPU, doesn't matter what specs you've.

The reason is probably a lot of subscribers and updates published to them:

```
# TYPE mercure_subscribers gauge
mercure_subscribers 4299
# HELP mercure_subscribers_total Total number of handled subscribers
# TYPE mercure_subscribers_total counter
mercure_subscribers_total 2.939146e+06
# HELP mercure_updates_total Total number of handled updates
# TYPE mercure_updates_total counter
mercure_updates_total 7.891176e+06
```

This is just for 2 days, this is a reduced amount, normally it's up to x4 of updates that are currently disabled.

Here is debug profile of CPU:
```
File: caddy
Type: cpu
Time: Aug 26, 2021 at 6:53am
Duration: 300.16s, Total samples = 461.92s (153.89%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 231.78s, 50.18% of 461.92s total
Dropped 1620 nodes (cum <= 2.31s)
Showing top 10 nodes out of 141
      flat  flat%   sum%        cum   cum%
    55.77s 12.07% 12.07%    191.39s 41.43%  runtime.selectgo
    41.19s  8.92% 20.99%     52.73s 11.42%  runtime.sellock
    24.36s  5.27% 26.26%     24.40s  5.28%  runtime.(*waitq).dequeue (inline)
    22.55s  4.88% 31.15%    114.28s 24.74%  github.com/dunglas/mercure.(*Subscriber).CanDispatch
    18.83s  4.08% 35.22%     18.83s  4.08%  go.uber.org/zap.(*Logger).check
    16.90s  3.66% 38.88%     17.25s  3.73%  runtime.unlock2
    14.31s  3.10% 41.98%     32.20s  6.97%  github.com/dunglas/mercure.canReceive
    13.21s  2.86% 44.84%     13.21s  2.86%  runtime.empty
    12.48s  2.70% 47.54%     44.65s  9.67%  runtime.schedule
    12.18s  2.64% 50.18%     12.64s  2.74%  runtime.gopark
```
[pprof.caddy.samples.cpu.006.pb.gz](https://github.com/dunglas/mercure/files/7103058/pprof.caddy.samples.cpu.006.pb.gz)

Here is the image of it:
![dump1](https://user-images.githubusercontent.com/48183131/131874372-28094f39-e4e8-40dc-a31f-6dfe5c0bfcd3.png)

The problematic lines are:

https://github.com/dunglas/mercure/blob/ca2df66f27356aa2511ef4f959fc4156a0f69a94/subscriber.go#L68-L102

At first, we thought the problem is with `Zap(*Logger) check` but PR https://github.com/dunglas/mercure/pull/554 should fix it.

Anyways, completely removing Zap logging, the situation didn't improve but instead showed more problems with `runtime.selectgo`

Here is debug profile of CPU:
```
File: caddy
Type: cpu
Time: Aug 31, 2021 at 12:27pm
Duration: 300.10s, Total samples = 568.67s (189.49%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 347.87s, 61.17% of 568.67s total
Dropped 1614 nodes (cum <= 2.84s)
Showing top 10 nodes out of 116
      flat  flat%   sum%        cum   cum%
    76.58s 13.47% 13.47%    263.92s 46.41%  runtime.selectgo
    50.10s  8.81% 22.28%     50.28s  8.84%  runtime.(*waitq).dequeue (inline)
    47.13s  8.29% 30.56%     59.44s 10.45%  runtime.sellock
    29.29s  5.15% 35.71%     29.29s  5.15%  memeqbody
    29.05s  5.11% 40.82%     86.37s 15.19%  github.com/dunglas/mercure.(*Subscriber).CanDispatch
    28.25s  4.97% 45.79%    166.05s 29.20%  github.com/dunglas/mercure.(*Subscriber).Dispatch
    25.76s  4.53% 50.32%     57.32s 10.08%  github.com/dunglas/mercure.canReceive
    25.14s  4.42% 54.74%     25.14s  4.42%  runtime.empty (inline)
    18.58s  3.27% 58.01%     19.21s  3.38%  runtime.gopark
    17.99s  3.16% 61.17%     17.99s  3.16%  runtime.(*gQueue).pop
```

Here is the image of it:
![dump2](https://user-images.githubusercontent.com/48183131/131874958-c2aeb3cf-348e-41fa-9ebd-f9f2f9a9f60c.png)

Sorry, I can't write a benchmark for it but ready to test what changes is needed.

Data posted to Mercure is always to different topics.

Posted to topics:
/users/613193cee6be0e1016042334

Private: true

Data:
```
{
	"@context": "/contexts/User",
	"@id": "/users/613193cee6be0e1016042334",
	"@type": "User",
	"id": "613193cee6be0e1016042334",
	"quota": 40000,
	"used": 7186,
	"isDisabled": false,
	"isDeleted": false,
	"createdAt": "2021-09-03T05:17:34+02:00",
	"updatedAt": "2021-09-03T05:18:29+02:00"
}
```

Thanks!

**Comment by dunglas** [comment]
Note: as discussed privately and shown in the second profile, disabling the presence API helps a bit.

I'm not sure of what we can optimize here. I double-checked that we don't loop over a closed chan (which eats CPU because a closed chan doesn't block), but I cannot find a pattern like this. `CanDispatch()` can probably be optimized a bit, but otherwise I don't see what can cause the issue here.

**Comment by dunglas** [comment]
I wonder if it's just not the intended behavior. You have many subscribers and updates are following at a huge rate. Every time an update is received, the server must loop over all subscribers to dispatch it, and check if the subscriber is authorized to receive this update. This operation will always eat CPU.

I wonder if the solution isn't just to keep the number of subscribers lower by splitting it across different servers (horizontal scalability instead of vertical). It's exactly the purpose of the On Prem version, I can send you a demo license if you want to try.

Anyway, I'm very open to merge any optimization we can make on this code.

**Comment by kevburnsjr** [comment]
`nextUpdate` doesn't block. It always returns nil.  
This means your program is pushing nil into the `outChan` on every cycle of the for loop. 
Sleeping for 1 second when both buffers are empty should eliminate your 100% CPU problem.

```go
func (s *Subscriber) nextUpdate() *Update {

	// ...
	
	time.Sleep(time.Second)
	return nil
}
```

Removing those buffers and using buffered channels instead could eliminate the sleep.

Also, truncating the first item of a slice causes the entire slice to be copied. - 
```go
// O(n)
s.live.buffer = []*Update{}
s.live.buffer = append(s.live.buffer, u)
u := s.live.buffer[0]
s.live.buffer = s.live.buffer[1:] 
```
Better to use a linked list: `container/list`
```go
// O(1)
s.live.buffer := list.New()
s.live.buffer.PushBack(u)
u := s.live.buffer.Remove(s.live.buffer.Front()).(*Update)
```

**Comment by divine** [comment]
Hello @kevburnsjr,

I have applied your suggested changes but looks like I made somewhere an error, could you please help as I don't understand GO well and still learning?

This doesn't send currently notifications and test is failing:

```bash
=== RUN   TestDispatch
    subscriber_test.go:27: 
        	Error Trace:	subscriber_test.go:27
        	Error:      	Not equal: 
        	            	expected: "1"
        	            	actual  : "3"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-1
        	            	+3
        	Test:       	TestDispatch
    subscriber_test.go:27: 
        	Error Trace:	subscriber_test.go:27
        	Error:      	Not equal: 
        	            	expected: "2"
        	            	actual  : "3"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-2
        	            	+3
        	Test:       	TestDispatch
```

Here is the git diff:
```diff
@@ -1,6 +1,7 @@
 package mercure

 import (
+       "container/list"
        "fmt"
        "net/url"
        "sync"
@@ -12,7 +13,7 @@ import (

 type updateSource struct {
        in     chan *Update
-       buffer []*Update
+       buffer *list.List
 }

 // Subscriber represents a client subscribed to a list of topics.
@@ -47,8 +48,8 @@ func NewSubscriber(lastEventID string, logger Logger, tss *TopicSelectorStore) *

                responseLastEventID: make(chan string, 1),

-               history:            updateSource{},
-               live:               updateSource{in: make(chan *Update)},
+               history:            updateSource{buffer: list.New()},
+               live:               updateSource{in: make(chan *Update), buffer: list.New()},
                out:                make(chan *Update),
                disconnected:       make(chan struct{}),
                logger:             logger,
@@ -74,7 +75,7 @@ func (s *Subscriber) start() {
                                break
                        }
                        if s.CanDispatch(u) {
-                               s.history.buffer = append(s.history.buffer, u)
+                               s.history.buffer.PushBack(u)
                        }
                case u, ok := <-s.live.in:
                        if !ok {
@@ -84,16 +85,16 @@ func (s *Subscriber) start() {
                                return
                        }
                        if s.CanDispatch(u) {
-                               s.live.buffer = append(s.live.buffer, u)
+                               s.live.buffer.PushBack(u)
                        }
                case s.outChan() <- s.nextUpdate():
-                       if len(s.history.buffer) > 0 {
-                               s.history.buffer = s.history.buffer[1:]
+                       if s.history.buffer.Len() > 0 {
+                               s.history.buffer.Remove(s.history.buffer.Front())

                                break
                        }

-                       s.live.buffer = s.live.buffer[1:]
+                       s.live.buffer.Remove(s.live.buffer.Front())
                case <-s.disconnected:
                        close(s.out)

@@ -103,8 +104,8 @@ func (s *Subscriber) start() {
 }

 // outChan returns the out channel if buffers aren't empty, or nil to block.
-func (s *Subscriber) outChan() chan<- *Update {
-       if len(s.live.buffer) > 0 || len(s.history.buffer) > 0 {
+func (s *Subscriber) outChan() chan *Update {
+       if s.live.buffer.Len() > 0 || s.history.buffer.Len() > 0 {
                return s.out
        }

@@ -115,16 +116,16 @@ func (s *Subscriber) outChan() chan<- *Update {
 // The history is always entirely flushed before starting to dispatch live updates.
 func (s *Subscriber) nextUpdate() *Update {
        // Always flush the history buffer first to preserve order
-       if s.history.in != nil || len(s.history.buffer) > 0 {
-               if len(s.history.buffer) > 0 {
-                       return s.history.buffer[0]
+       if s.history.in != nil || s.history.buffer.Len() > 0 {
+               if s.history.buffer.Len() > 0 {
+                       return s.history.buffer.Remove(s.live.buffer.Front()).(*Update)
                }

                return nil
        }

-       if len(s.live.buffer) > 0 {
-               return s.live.buffer[0]
+       if s.live.buffer.Len() > 0 {
+               return s.live.buffer.Remove(s.live.buffer.Front()).(*Update)
        }

        return nil

```

Thanks!

**Comment by kevburnsjr** [comment]
Very close. The tests are failing because the front element is being removed twice.  
Removing all the code in the case statement should fix the problem.
```go
		case s.outChan() <- s.nextUpdate():
			// empty
```

**Comment by divine** [comment]
> Very close. The tests are failing because the front element is being removed twice.
> Removing all the code in the case statement should fix the problem.
> 
> ```go
> 		case s.outChan() <- s.nextUpdate():
> 			// empty
> ```

Hello @kevburnsjr,

Thank you for your clarification and help.

Sorry about asking you again but still an issue even after removing that line:

```bash
=== RUN   TestDispatch
    subscriber_test.go:27: 
        	Error Trace:	subscriber_test.go:27
        	Error:      	Not equal: 
        	            	expected: "1"
        	            	actual  : "3"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-1
        	            	+3
        	Test:       	TestDispatch
    subscriber_test.go:27: 
        	Error Trace:	subscriber_test.go:27
        	Error:      	Not equal: 
        	            	expected: "2"
        	            	actual  : "3"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-2
        	            	+3
        	Test:       	TestDispatch
    subscriber_test.go:27: 
        	Error Trace:	subscriber_test.go:27
        	Error:      	Not equal: 
        	            	expected: "4"
        	            	actual  : "3"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-4
        	            	+3
        	Test:       	TestDispatch
--- FAIL: TestDispatch (0.00s)
```

git diff:

```diff
diff --git a/subscriber.go b/subscriber.go
index c6d33aa..5ac60f2 100644
--- a/subscriber.go
+++ b/subscriber.go
@@ -1,6 +1,7 @@
 package mercure

 import (
+       "container/list"
        "fmt"
        "net/url"
        "sync"
@@ -12,7 +13,7 @@ import (

 type updateSource struct {
        in     chan *Update
-       buffer []*Update
+       buffer *list.List
 }

 // Subscriber represents a client subscribed to a list of topics.
@@ -47,8 +48,8 @@ func NewSubscriber(lastEventID string, logger Logger, tss *TopicSelectorStore) *

                responseLastEventID: make(chan string, 1),

-               history:            updateSource{},
-               live:               updateSource{in: make(chan *Update)},
+               history:            updateSource{buffer: list.New()},
+               live:               updateSource{in: make(chan *Update), buffer: list.New()},
                out:                make(chan *Update),
                disconnected:       make(chan struct{}),
                logger:             logger,
@@ -74,7 +75,7 @@ func (s *Subscriber) start() {
                                break
                        }
                        if s.CanDispatch(u) {
-                               s.history.buffer = append(s.history.buffer, u)
+                               s.history.buffer.PushBack(u)
                        }
                case u, ok := <-s.live.in:
                        if !ok {
@@ -84,16 +85,9 @@ func (s *Subscriber) start() {
                                return
                        }
                        if s.CanDispatch(u) {
-                               s.live.buffer = append(s.live.buffer, u)
+                               s.live.buffer.PushBack(u)
                        }
                case s.outChan() <- s.nextUpdate():
-                       if len(s.history.buffer) > 0 {
-                               s.history.buffer = s.history.buffer[1:]
-
-                               break
-                       }
-
-                       s.live.buffer = s.live.buffer[1:]
                case <-s.disconnected:
                        close(s.out)

@@ -103,8 +97,8 @@ func (s *Subscriber) start() {
 }

 // outChan returns the out channel if buffers aren't empty, or nil to block.
-func (s *Subscriber) outChan() chan<- *Update {
-       if len(s.live.buffer) > 0 || len(s.history.buffer) > 0 {
+func (s *Subscriber) outChan() chan *Update {
+       if s.live.buffer.Len() > 0 || s.history.buffer.Len() > 0 {
                return s.out
        }

@@ -115,16 +109,16 @@ func (s *Subscriber) outChan() chan<- *Update {
 // The history is always entirely flushed before starting to dispatch live updates.
 func (s *Subscriber) nextUpdate() *Update {
        // Always flush the history buffer first to preserve order
-       if s.history.in != nil || len(s.history.buffer) > 0 {
-               if len(s.history.buffer) > 0 {
-                       return s.history.buffer[0]
+       if s.history.in != nil || s.history.buffer.Len() > 0 {
+               if s.history.buffer.Len() > 0 {
+                       return s.history.buffer.Remove(s.live.buffer.Front()).(*Update)
                }

                return nil
        }

-       if len(s.live.buffer) > 0 {
-               return s.live.buffer[0]
+       if s.live.buffer.Len() > 0 {
+               return s.live.buffer.Remove(s.live.buffer.Front()).(*Update)
        }

        return nil

```

Thanks!

**Comment by darthShadow** [comment]
The problem looks to be in the `nextUpdate()` function, if I am not wrong.

Earlier, it was simply returning the first element via `return s.history.buffer[0]` or `return s.live.buffer[0]`.

These have now been changed to `list.Remove` calls, which seems wrong.

`return s.history.buffer.Remove(s.live.buffer.Front()).(*Update)` should instead be `return s.history.buffer.Front().Value.(*Update)`.

NOTE: There is also a typo above where we get the first element of the live buffer but remove it from the history buffer.

Similarly, `return s.live.buffer.Remove(s.live.buffer.Front()).(*Update)` should instead be `s.live.buffer.Front().Value.(*Update)`

**Comment by egonelbre** [comment]
@kevburnsjr linked list is almost always worse choice than a slice, especially for small items. Neither append nor slicing an existing slice is O(n) -- append is O(n) in the worst-case and O(1), with few ns in the common case. Slicing a slice is always O(1). I've seen 2x and more speedups from replacing a `list.List` with a slice. If you don't believe, then write a benchmark. AFAIR, list.List becomes better than a slice only when you have 10k+ items -- although the exact number might have changed at this point.

If you are looking for a faster replacement for a slice in this case, then a proper deque implementation would be https://github.com/karalabe/cookiejar/blob/master/collections/deque/deque.go (you would need to specialize it for your use-case). This will end up working faster either than list.List or a slice.

**Comment by kevburnsjr** [comment]
@egonelbre is right. I was mistaken.
https://gist.github.com/kevburnsjr/1ed973e6b1fd332c5c38d108abce142b

**Comment by divine** [comment]
> @egonelbre is right. I was mistaken.
> https://gist.github.com/kevburnsjr/1ed973e6b1fd332c5c38d108abce142b

Thank you for the test, I've added the [deque](https://github.com/gammazero/deque) package, looks much better, what do you think guys?

https://gist.github.com/divine/8779e10fcbb3c77123795f41811fef71

Thanks!

**Comment by egonelbre** [comment]
@divine if you specialize the deque package for a particular item, it will be faster.

**Comment by divine** [comment]
Hello,

Having tested in a production, I can say for sure slices are much faster and the benchmark that I wrote shows exactly the same thing:

without the deque:
```bash
BenchmarkDispatch
BenchmarkDispatch-8   	  800042	      1290 ns/op
PASS

```
with the deque:
```bash
BenchmarkDispatch
BenchmarkDispatch-8   	  920971	      1393 ns/op
PASS (edited) 
```

So basically, the issue isn't related to slices, it's somewhere else...


Thanks!

**Comment by dunglas** [comment]
Thanks for having investigated @divine!

**Comment by kevburnsjr** [comment]
I felt bad today about wasting your time with bad advice (`container/list`). So rather than working on my other side project today, I spent the day whipping up a 6 dimensional bench test against the subscriber.

Draft PR: https://github.com/kevburnsjr/mercure/pull/1
Branch: https://github.com/kevburnsjr/mercure/tree/subscriber-performance
Results: [results.txt](https://gist.githubusercontent.com/kevburnsjr/7312c0007aef3db5816129f38c249513/raw/1c4240e3911f54cc8689719ab2e00ef04eabdb02/gistfile1.txt)

## Findings

1. There are two separate scheduler contention problems (select priority queue and Ristretto) that are interfering with one another in a really nasty way at high concurrency.

2. The select priority queue is burning all the CPU according to your graphs so rather than trying to optimize it, I just [deleted](https://www.youtube.com/watch?v=t705r8ICkRw&t=795s) it. I'm pretty sure it's only used to replay history before live events when the subscriber first connects to ensure that subscribers receive all events in the correct order. Whether it actually achieves that objective is debatable. Replacing it with a live update buffer that's only used when the subscriber is catching up on its history should be no biggie.

3. Ristretto is an LFU cache (least frequently used). This is nice when you have a bunch of large objects that are costly to reproduce but not very nice when you have very small values (like literally just a boolean). Every read to an LFU triggers multiple writes to underlying data structures which all require locks and you have to scan to find things to evict based on size. It's a lot more complicated than a sharded LRU which exhibits much better performance for this workload (1 write per read).

4. The order of the cache reads was incorrect, causing twice as many Ristretto hits as necessary. See [here](https://github.com/dunglas/mercure/blob/5c06d440d421a8f27321d962762bccdeee16a5d1/topic_selector.go#L49-L61) it retrieves the RegExp just before it returns a hit on the boolean and the regexp is not used. This is significant because this is in the hot path for cached content and it's not normally a problem because Ristretto is crazy fast but at very high concurrency it melts so the extra call contributes to instability. Reordering these statements is the least obtrusive of the remedies contained within this forthcoming PR.

## Running the bench test

It's a multidimensional benchmark test so it runs 216 different combinations across different values for 6 different variants: 3 workload variants and 3 solution variants.

- (workload variant) Number of topics subscribed
- (workload variant) Number of subscribers
- (workload variant) Percentage of messages delivered to subscribers
- (solution variant) Whether to skip the bypass select priority queue
- (solution variant) Which cache to use (Ristretto or LRU)
- (solution variant) How many shards to give the LRU cache (Ristretto is hard coded to 256)

The most sensitive workload variant by far is the number of topics subscribed. The O(n^2) nested loop performing cached regular expression evaluation gets exponentially worse the more topics are being listened to and updated. It is not known precisely what values the reference workload is seeing but this parameter affects both subscribers and update messages equally for the purposes of this test so a value of 10 means each subscriber has to 10 topic selectors and each update has 10 topics. Each matching update matches the middle update topic, so: 

- 1 topics = 1 x 1 / 2 = 1 topic evaluation
- 5 topics = 5 x 5 / 2 = 12 topic evaluations
- 10 topics = 10 x 10 / 2 = 50 topic evaluations
- 20 topics = 20 x 20 / 2 = 200 topic evaluations

## Did we succeed at reproducing the problem?

- The huge differences observed in processing time and memory allocation frequency for different levels of concurrency with different numbers of topics is strong evidence that this is the problem observed by the reporter of this issue.

## Did we fix the problem?

Comparing the best solution variant combination against the worst solution variant combination, we see very compelling evidence that this change will:

1. **Increase latency** when the system is under low contention
    - On the order of 0.5μs
    
2. **Increase throughput** when the system is under high contention
    - On the order of 20-50x efficiency improvement 
    - In this area of the code 
    - For highly concurrent workloads 
    - Which is the goal of any social network
   
At the bottom of the bench test file you will find [these instructions](https://gist.github.com/kevburnsjr/3ebe085a4741487a05a9b1c2379ba68b) on how to run any subset of the commands to generate a diff or pdf for specific combinations of variants.

```
SUB_TEST_CONCURRENCY=5000 \
SUB_TEST_SKIPSELECT=false \
SUB_TEST_CACHE=ristretto \
SUB_TEST_SHARDS=256 \
go test -bench=. -run=BenchmarkSubscriber -benchmem -count 5 | tee _dist/output.5kc.noskip.ristretto.256.txt

SUB_TEST_CONCURRENCY=5000 \
SUB_TEST_SKIPSELECT=true \
SUB_TEST_CACHE=lru \
SUB_TEST_SHARDS=256 \
go test -bench=. -run=BenchmarkSubscriber -benchmem -count 5 | tee _dist/output.5kc.skip.lru.256.txt

benchstat _dist/output.5kc.noskip.ristretto.256.txt \
          _dist/output.5kc.skip.lru.256.txt \
        > _dist/diff-cache.5kc.256.txt
```
```
name                                  old time/op    new time/op    delta
Subscriber/topics_1_matchpct_1-12       1.51µs ± 2%    0.45µs ± 1%  -70.05%  (p=0.008 n=5+5)
Subscriber/topics_1_matchpct_10-12      1.44µs ± 1%    0.41µs ± 1%  -71.30%  (p=0.008 n=5+5)
Subscriber/topics_1_matchpct_100-12     1.68µs ± 1%    0.49µs ± 1%  -70.59%  (p=0.008 n=5+5)
Subscriber/topics_5_matchpct_1-12        167µs ± 1%       5µs ± 0%  -97.06%  (p=0.008 n=5+5)
Subscriber/topics_5_matchpct_10-12       129µs ± 1%       5µs ± 2%  -96.33%  (p=0.008 n=5+5)
Subscriber/topics_5_matchpct_100-12     31.6µs ± 1%     2.7µs ± 4%  -91.56%  (p=0.008 n=5+5)
Subscriber/topics_10_matchpct_1-12      1.10ms ± 1%    0.02ms ±11%  -98.06%  (p=0.008 n=5+5)
Subscriber/topics_10_matchpct_10-12     1.17ms ± 1%    0.02ms ± 3%  -98.35%  (p=0.008 n=5+5)
Subscriber/topics_10_matchpct_100-12     676µs ± 1%      12µs ± 2%  -98.30%  (p=0.008 n=5+5)

name                                  old alloc/op   new alloc/op   delta
Subscriber/topics_1_matchpct_1-12         288B ± 0%      416B ± 0%  +44.44%  (p=0.008 n=5+5)
Subscriber/topics_1_matchpct_10-12        289B ± 0%      416B ± 0%  +43.94%  (p=0.008 n=5+5)
Subscriber/topics_1_matchpct_100-12       318B ± 0%      416B ± 0%  +30.92%  (p=0.016 n=4+5)
Subscriber/topics_5_matchpct_1-12        131kB ± 1%       8kB ± 0%  -93.86%  (p=0.008 n=5+5)
Subscriber/topics_5_matchpct_10-12       100kB ± 1%       8kB ± 0%  -92.33%  (p=0.008 n=5+5)
Subscriber/topics_5_matchpct_100-12     21.6kB ± 1%     4.3kB ± 0%  -80.29%  (p=0.008 n=5+5)
Subscriber/topics_10_matchpct_1-12       881kB ± 1%      32kB ± 0%  -96.39%  (p=0.016 n=5+4)
Subscriber/topics_10_matchpct_10-12      938kB ± 0%      31kB ± 0%  -96.75%  (p=0.008 n=5+5)
Subscriber/topics_10_matchpct_100-12     549kB ± 0%      18kB ± 0%  -96.72%  (p=0.008 n=5+5)

name                                  old allocs/op  new allocs/op  delta
Subscriber/topics_1_matchpct_1-12         5.00 ± 0%      7.00 ± 0%  +40.00%  (p=0.008 n=5+5)
Subscriber/topics_1_matchpct_10-12        5.00 ± 0%      7.00 ± 0%  +40.00%  (p=0.008 n=5+5)
Subscriber/topics_1_matchpct_100-12       5.00 ± 0%      7.00 ± 0%  +40.00%  (p=0.008 n=5+5)
Subscriber/topics_5_matchpct_1-12        1.50k ± 1%     0.15k ± 0%  -90.03%  (p=0.008 n=5+5)
Subscriber/topics_5_matchpct_10-12       1.17k ± 1%     0.14k ± 0%  -87.79%  (p=0.008 n=5+5)
Subscriber/topics_5_matchpct_100-12        260 ± 1%        79 ± 0%  -69.59%  (p=0.008 n=5+5)
Subscriber/topics_10_matchpct_1-12       10.0k ± 1%      0.6k ± 0%  -94.04%  (p=0.008 n=5+5)
Subscriber/topics_10_matchpct_10-12      10.6k ± 0%      0.6k ± 0%  -94.62%  (p=0.008 n=5+5)
Subscriber/topics_10_matchpct_100-12     6.08k ± 0%     0.34k ± 0%  -94.46%  (p=0.008 n=5+5)
```
Going from 10,000 allocations per op to 300 is pretty compelling.
```

BenchmarkSubscriber/topics_10_concurrency_20000_matchpct_1_skipselect_false_cache_ristretto_shards_256-12           1267           1263500 ns/op          992627 B/op      10997 allocs/op
BenchmarkSubscriber/topics_10_concurrency_20000_matchpct_1_skipselect_false_cache_lru_shards_1-12                  17701             67588 ns/op           31808 B/op        595 allocs/op
BenchmarkSubscriber/topics_10_concurrency_20000_matchpct_1_skipselect_false_cache_lru_shards_256-12                16388             73210 ns/op           31805 B/op        595 allocs/op
BenchmarkSubscriber/topics_10_concurrency_20000_matchpct_1_skipselect_true_cache_ristretto_shards_256-12            8466            211359 ns/op          932973 B/op       9768 allocs/op
BenchmarkSubscriber/topics_10_concurrency_20000_matchpct_1_skipselect_true_cache_lru_shards_1-12                   13573             88273 ns/op           31797 B/op        595 allocs/op
BenchmarkSubscriber/topics_10_concurrency_20000_matchpct_1_skipselect_true_cache_lru_shards_256-12                 93186             13118 ns/op           31812 B/op        595 allocs/op
BenchmarkSubscriber/topics_10_concurrency_20000_matchpct_10_skipselect_false_cache_ristretto_shards_256-12          1946           1247867 ns/op          986580 B/op      11028 allocs/op
BenchmarkSubscriber/topics_10_concurrency_20000_matchpct_10_skipselect_false_cache_lru_shards_1-12                 18100             65794 ns/op           30479 B/op        570 allocs/op
BenchmarkSubscriber/topics_10_concurrency_20000_matchpct_10_skipselect_false_cache_lru_shards_256-12               16902             70996 ns/op           30472 B/op        570 allocs/op
BenchmarkSubscriber/topics_10_concurrency_20000_matchpct_10_skipselect_true_cache_ristretto_shards_256-12          10000            213162 ns/op          886757 B/op       9298 allocs/op
BenchmarkSubscriber/topics_10_concurrency_20000_matchpct_10_skipselect_true_cache_lru_shards_1-12                  12656             88255 ns/op           30480 B/op        570 allocs/op
BenchmarkSubscriber/topics_10_concurrency_20000_matchpct_10_skipselect_true_cache_lru_shards_256-12               107236             11729 ns/op           30537 B/op        571 allocs/op
BenchmarkSubscriber/topics_10_concurrency_20000_matchpct_100_skipselect_false_cache_ristretto_shards_256-12         2083            644970 ns/op          522779 B/op       5816 allocs/op
BenchmarkSubscriber/topics_10_concurrency_20000_matchpct_100_skipselect_false_cache_lru_shards_1-12                29319             40647 ns/op           18047 B/op        336 allocs/op
BenchmarkSubscriber/topics_10_concurrency_20000_matchpct_100_skipselect_false_cache_lru_shards_256-12              25880             44691 ns/op           18049 B/op        336 allocs/op
BenchmarkSubscriber/topics_10_concurrency_20000_matchpct_100_skipselect_true_cache_ristretto_shards_256-12          9454            151316 ns/op          519969 B/op       5532 allocs/op
BenchmarkSubscriber/topics_10_concurrency_20000_matchpct_100_skipselect_true_cache_lru_shards_1-12                 25426             49033 ns/op           18016 B/op        337 allocs/op
BenchmarkSubscriber/topics_10_concurrency_20000_matchpct_100_skipselect_true_cache_lru_shards_256-12              174309              7469 ns/op           18016 B/op        337 allocs/op
```

## Usage

1. Grab the branch and merge it into yours

```
git remote add kevburnsjr https://github.com/kevburnsjr/mercure.git
git fetch kevburnsjr subscriber-performance
git merge subscriber-performance
```

2. Push your branch to production

3. Set new command line flag `-yolo` (alias of  `-perf-experiment`)
    - This switches to use the LRU with good defaults (boolean)

4. Optionally tune new int64 command line parameter `-tcsz`(alias of `-topic-cache-shard-size`)
    - The default is `1e4`. (10,000 * 256 shards = 2.5million entries)
    - Try the default first before bumping to `1e5` if you've got a lot of ram.
    - Anywhere up to `1e6` is reasonable. 

I'm on California time at the moment but I should be available tomorrow starting around 10am to answer any questions you might have if pushing to prod on a Sunday is your sort of thing. 😄

**Comment by kevburnsjr** [comment]
Just pushed a few more updates (fixed build issues caused by new cli params).

**Comment by divine** [comment]
Hello,

I just wanted to say thank you to all of you and personally @kevburnsjr for fixing the problem.

@kevburnsjr your draft PR indeed fixes the problem I was having, pushed to prod on Sunday - works well and **amazingly fast** with only %8-%10 of CPU usage!

I have just replied in your draft PR with a small issue about local transport, otherwise looks great!

Thanks!

**Comment by kevburnsjr** [comment]
@divine Glad to hear it! Would love to see any graphs if you've got 'em. I do it for the graphs.

@dunglas This new optimized code path is presently exposed as:
- 2 optional runtime flags in Go
    - `-yolo` enables performance experiment for topic selector store cache (default false)
    - `-tcsz` size of each shard in topic selector store cache (default 10,000)
- 1 optional config parameter in Caddy. 
```
// Triggers use of LRU topic selector cache and avoidance of select priority queue (recommend 10,000 - 1,000,000)
LruShardSize *int64 `json:"lru_shard_size,omitempty"`
```

I'd like to:

1. Submit a PR that keeps the new performance experiment hidden behind these optional config params for now
2. Submit a second PR that removes Ristretto and makes the new code path the default

This should allow us to gather more data points from other customers to ensure this new path really is better for all use cases. 
Once that has been determined, the second PR will already be ready to merge.

Do you have any additional feedback about these configuration parameters or test coverage I'd be happy to polish them off.

A single paramter `-tcsz` should be sufficient as it is with Caddy.
Before submitting I'll probably remove the `-yolo` flag and change the `-tcsz` default to 0.

**Comment by divine** [comment]
> @divine Glad to hear it! Would love to see any graphs if you've got 'em. I do it for the graphs.

Yup, I have posted them in your draft PR as well it here:
![image](https://user-images.githubusercontent.com/48183131/133010591-147d2113-ae6a-4759-8a18-461c866447a8.png)


> This should allow us to gather more data points from other customers to ensure this new path really is better for all use cases.
> Once that has been determined, the second PR will already be ready to merge.

We've talked privately with @dunglas and he came to the conclusion I'm the probably only one of those big users who is running a few million notifications per day on this open-source version.

Having a high amount of notifications just showed the possible leaks such as the [memory one](https://github.com/dunglas/mercure/issues/463#issuecomment-825580196) that got fixed and this CPU one which is fixed by you.

These changes probably will make sense for all use cases since it's basically performance improvement.

Thanks!
